version: '3.9'

volumes:
  local_postgres_data:
  local_migration_data:

services:
  migrations:
    build: .
    env_file:
      - .env
    command: python todolist/manage.py migrate
    volumes:
      - ./local_migration_data:/var/lib/postgresql/data/migrations/
    depends_on:
      postgres:
        condition: service_healthy

  api:
    build: .
    env_file:
      - .env
    command: python todolist/manage.py runserver 0.0.0.0:8000
    depends_on:
      postgres:
        condition: service_healthy
      migrations:
        condition: service_completed_successfully
    ports:
      - "8000:8000"

  postgres:
    image: postgres:latest
    volumes:
      - ./local_postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "5432:5432"
    restart: "always"
    healthcheck:
      test: /usr/bin/pg_isready
      interval: 5s
      timeout: 5s
      retries: 5

  front:
    image: sermalenk/skypro-front:lesson-37
    depends_on:
      - api
    ports:
      - "80:80"