# Generated by Django 4.2.1 on 2023-06-28 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0005_alter_comment_goal_alter_comment_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='due_date',
            field=models.DateTimeField(null=True, verbose_name='Дата дедлайна'),
        ),
    ]
