# Generated by Django 4.2.3 on 2023-07-06 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0010_alter_goalcategory_board'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='description',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
    ]
