# Generated by Django 4.2.1 on 2023-07-04 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tguser',
            name='tg_user',
            field=models.CharField(verbose_name='ID пользователя Telegram'),
        ),
    ]
