version: '3.9'

volumes:
  local_postgres_data:
  local_migration_data:

services:
  migrate:
    image: zeroxfuumanze/django_app
    env_file:
      - ../.env
    command: python manage.py migrate
    volumes:
      - local_migration_data:/migrations/
    depends_on:
      db:
        condition: service_healthy

  api:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      db:
        condition: service_healthy
      migrate:
        condition: service_completed_successfully
    env_file:
      - ../.env
    ports:
      - "8000:8000"

  db:
    image: postgres:latest
    volumes:
      - local_postgres_data:/var/lib/postgresql/data
    env_file:
      - ../.env
    ports:
      - "5432:5432"
    restart: "always"
    healthcheck:
      test: /usr/bin/pg_isready
      interval: 5s
      timeout: 5s
      retries: 5

  front:
    image: sermalenk/skypro-front:lesson-34
    depends_on:
      - api
    ports:
      - "80:80"